---
variables:
  GET_SOURCES_ATTEMPTS: "3"
  GIT_SUBMODULE_STRATEGY: "recursive"

stages:
  - build
  - release

.crossrs-build-template:
  image: ghcr.io/cross-rs/$CARGO_BUILD_TARGET:main
  stage: build
  dependencies: []
  before_script:
    - export RUSTUP_HOME="${PWD}/.rustup_cache"
    - export CARGO_HOME="${PWD}/.cargo_cache"
    - curl -f https://sh.rustup.rs | sh -s -- -y --no-modify-path
    - source "$CARGO_HOME/env"
    - rustup target add $CARGO_BUILD_TARGET
  script:
    - cargo build --release --target $CARGO_BUILD_TARGET
  artifacts:
    paths:
      - target/$CARGO_BUILD_TARGET/release/domcp
  cache:
    key: cache-$CI_JOB_NAME_SLUG
    paths:
      - .rustup_cache/
      - .cargo_cache/
      - target/

package x86_64 linux static:
  extends: [.crossrs-build-template]
  variables:
    CARGO_BUILD_TARGET: x86_64-unknown-linux-musl

package aarch64 linux static:
  extends: [.crossrs-build-template]
  variables:
    CARGO_BUILD_TARGET: aarch64-unknown-linux-musl

package armv7 linux static:
  extends: [.crossrs-build-template]
  variables:
    CARGO_BUILD_TARGET: armv7-unknown-linux-musleabihf

package riscv64 linux static:
  extends: [.crossrs-build-template]
  variables:
    CARGO_BUILD_TARGET: riscv64gc-unknown-linux-musl

# Windows needs special care
package x86_64 windows msvc:
  extends: [.crossrs-build-template]
  image: docker.io/aloismisery/x86_64-pc-windows-msvc-cross:extra
  variables:
    CARGO_BUILD_TARGET: x86_64-pc-windows-msvc
  script:
    - cargo build --release --target $CARGO_BUILD_TARGET
    - wine target/$CARGO_BUILD_TARGET/release/domcp.exe --version
  artifacts:
    paths:
      - target/$CARGO_BUILD_TARGET/release/domcp.exe

package x86_64 debian:
  stage: build
  image: docker.io/library/debian:stable
  variables:
    DEBIAN_FRONTEND: noninteractive
    DEBEMAIL: kanedias@house-of-maker.online
  before_script:
    - apt-get update -qq
    - apt-get install --yes cargo rustc debhelper-compat git-buildpackage
  script:
    - cp -a packaging/debian/debian ./
    # generate changelog
    - gbp dch --ignore-branch
        --since="$(git describe --tags --abbrev=0 HEAD^)"
        --new-version="$(git describe --tags)"
        --distribution="stable"
        --urgency="medium"
        --spawn-editor=never
    # execute build
    - dpkg-buildpackage --build="binary"
        --unsigned-source
        --unsigned-changes
    # take the built packages from the parent dir
    - mkdir -pv dist/
    - mv -v ../*.deb* dist/
  artifacts:
    paths:
      - dist/*

release publish:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: package x86_64 linux static
    - job: package aarch64 linux static
    - job: package armv7 linux static
    - job: package riscv64 linux static
    - job: package x86_64 windows msvc
  image: registry.gitlab.com/gitlab-org/cli:latest
  variables:
    GLAB_ENABLE_CI_AUTOLOGIN: "true"
    PACKAGE_URL: $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/domcp/$CI_COMMIT_TAG
  before_script:
    - apk add --no-cache curl jq
  script:
    - glab release create "$CI_COMMIT_TAG" --notes "Release $CI_COMMIT_TAG"
    - | 
      for asset in target/*/release/domcp target/*/release/domcp.exe; do
        asset_name=$(basename $asset)
        release_dir=$(dirname $asset)
        target_dir=$(dirname $release_dir)
        target_name=$(basename $target_dir)

        # domcp.exe -> domcp-x86_64-pc-windows-msvc.exe
        registry_name=${asset_name/domcp/domcp-${target_name}}
        echo "Uploading $asset -> $PACKAGE_URL/${registry_name}"
        curl --fail-with-body --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
             --upload-file "$asset" "${PACKAGE_URL}/${registry_name}"
        link=$(jq -n \
          --arg name "domcp (${target_name})" \
          --arg url  "${PACKAGE_URL}/${registry_name}" \
          --arg path "/$asset" \
          '[{name: $name, url: $url, link_type: "package", direct_asset_path: $path}]')
        glab release upload "$CI_COMMIT_TAG" --assets-links="$link"
      done

cargo publish:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: package x86_64 linux static
      artifacts: false
    - job: package x86_64 windows msvc
      artifacts: false
  image: docker.io/library/rust:alpine
  script:
    - cargo publish --token ${CARGO_PUBLISH_TOKEN}
