use crate::packages;
use anyhow::{Result, bail};
use log::debug;
/// The kind of package runner detected from the command.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Runner {
    /// Python — `uvx` (from the `uv` tool)
    Uvx,
    /// Python — `pipx`
    Pipx,
    /// Node.js — `npx`
    Npx,
}

impl Runner {
    /// Detect the runner from the first token of the user command.
    pub fn detect(command: &str) -> Result<Self> {
        match command {
            "uvx" => Ok(Self::Uvx),
            "pipx" => Ok(Self::Pipx),
            "npx" => Ok(Self::Npx),
            other => bail!("Unsupported runner: `{other}`. domcp supports: uvx, pipx, npx"),
        }
    }

    /// Base Docker image for this runner.
    fn base_image(self) -> &'static str {
        "alpine:latest"
    }

    /// Environment variables to redirect tool caches to /tmp.
    fn env_vars(self) -> &'static str {
        match self {
            Self::Uvx => concat!("ENV UV_CACHE_DIR=/tmp/.cache/uv\n", "ENV HOME=/opt/home\n",),
            Self::Pipx => concat!(
                "ENV PIPX_HOME=/tmp/.local/pipx\n",
                "ENV PIPX_BIN_DIR=/tmp/.local/bin\n",
                "ENV HOME=/opt/home\n",
            ),
            Self::Npx => concat!("ENV npm_config_cache=/tmp/.npm\n", "ENV HOME=/opt/home\n",),
        }
    }

    /// Shell commands to install the runner itself.
    fn install_commands(self) -> &'static str {
        match self {
            Self::Uvx => "RUN apk add --no-cache python3 uv\n",
            Self::Pipx => "RUN apk add --no-cache python3 pipx\n",
            Self::Npx => "RUN apk add --no-cache npm\n",
        }
    }

    /// Common tools needed by packages running inside the container.
    fn common_install_commands(self) -> &'static str {
        "RUN apk add --no-cache coreutils\n"
    }
}

/// Generate a Dockerfile for the given runner and command.
///
/// The container is set up to:
/// - Use a minimal base image
/// - Install only the required runner
/// - Pre-install the MCP server package for faster start
/// - Run as non-root when possible
pub fn generate(
    runner: Runner,
    command: &[String],
    expose_port: Option<u16>,
    packages: &[String],
) -> Result<String> {
    debug!(
        "Generating Dockerfile for {:?} with command: {:?}",
        runner, command
    );

    let base = runner.base_image();
    let runner_install = runner.install_commands();
    let common_install = runner.common_install_commands();
    let entrypoint = build_entrypoint(runner, command);

    // Try to identify the package name to pre-install it into the image.
    // This makes container startup faster on subsequent runs.
    let preinstall = build_preinstall(runner, command);

    let env_vars = runner.env_vars();
    let version_label = env!("CARGO_PKG_VERSION");
    let packages_label = format!(
        "LABEL {}=\"{}\"",
        packages::PACKAGES_LABEL_KEY,
        packages::label_value(packages)
    );
    let extra_packages = if packages.is_empty() {
        String::new()
    } else {
        format!(
            "# Extra packages\nRUN apk add --no-cache {}\n",
            packages.join(" ")
        )
    };

    let expose = match expose_port {
        Some(port) => format!("EXPOSE {port}"),
        None => String::new(),
    };

    let dockerfile = format!(
        r#"# Auto-generated by domcp — do not edit
FROM {base}

LABEL org.opencontainers.image.source="domcp"
LABEL org.opencontainers.image.version="{version_label}"
{packages_label}

# Redirect tool caches to /tmp
{env_vars}
# Writable temp areas
RUN mkdir -p /opt/home /tmp/.cache /tmp/.local /tmp/.npm

# Install runner
{runner_install}
# Install common runtime tools
{common_install}
{extra_packages}

# Pre-install the MCP server package for faster startup
{preinstall}

RUN chmod -R 777 /opt/home /tmp/.cache /tmp/.local /tmp/.npm

{expose}
{entrypoint}
"#
    );

    debug!("Generated Dockerfile:\n{}", dockerfile);
    Ok(dockerfile)
}

/// Build a pre-install command to bake the MCP server package into the image.
fn build_preinstall(runner: Runner, command: &[String]) -> String {
    // Extract the package name (first non-flag argument after the runner).
    let package = command.iter().skip(1).find(|arg| !arg.starts_with('-'));

    match (runner, package) {
        (Runner::Uvx, Some(pkg)) => format!("RUN uv tool install {pkg}\n"),
        (Runner::Pipx, Some(pkg)) => format!("RUN pipx install {pkg}\n"),
        (Runner::Npx, Some(pkg)) => {
            // For npx, if the user used `-y` flag we can pre-install
            let has_yes = command.iter().any(|a| a == "-y" || a == "--yes");
            if has_yes {
                format!("RUN npm install -g {pkg}\n")
            } else {
                format!("# npx package: {pkg} (not pre-installed, no -y flag)\n")
            }
        }
        _ => "# No package detected to pre-install\n".to_string(),
    }
}

/// Build the ENTRYPOINT instruction for the Dockerfile.
fn build_entrypoint(runner: Runner, command: &[String]) -> String {
    // For npx with pre-installed global packages, we still use npx as the
    // entrypoint since it handles PATH resolution correctly.
    let parts: Vec<String> = match runner {
        Runner::Uvx => {
            // uvx runs as: uvx <package> [args...]
            command.to_vec()
        }
        Runner::Pipx => {
            // pipx run <package> [args...]
            let mut v = vec!["pipx".to_string(), "run".to_string()];
            v.extend(command.iter().skip(1).cloned());
            v
        }
        Runner::Npx => {
            // npx [flags] <package> [args...]
            command.to_vec()
        }
    };

    let json_parts: Vec<String> = parts.iter().map(|p| format!("\"{}\"", p)).collect();
    format!("ENTRYPOINT [{}]", json_parts.join(", "))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_detect_runners() {
        assert_eq!(Runner::detect("uvx").unwrap(), Runner::Uvx);
        assert_eq!(Runner::detect("npx").unwrap(), Runner::Npx);
        assert_eq!(Runner::detect("pipx").unwrap(), Runner::Pipx);
        assert!(Runner::detect("cargo").is_err());
    }

    #[test]
    fn test_generate_uvx() {
        let cmd = vec!["uvx".into(), "mcp-server-fetch".into()];
        let df = generate(Runner::Uvx, &cmd, None, &[]).unwrap();
        assert!(df.contains("FROM alpine:latest"));
        assert!(df.contains("apk add --no-cache python3 uv"));
        assert!(df.contains("RUN apk add --no-cache coreutils"));
        assert!(df.contains("uv tool install mcp-server-fetch"));
        assert!(df.contains("ENTRYPOINT [\"uvx\", \"mcp-server-fetch\"]"));
        assert!(df.contains(&format!(
            "LABEL org.opencontainers.image.version=\"{}\"",
            env!("CARGO_PKG_VERSION")
        )));
        assert!(df.contains("LABEL domcp.packages=\"\""));
        assert!(!df.contains("EXPOSE"));
    }

    #[test]
    fn test_generate_npx() {
        let cmd = vec![
            "npx".into(),
            "-y".into(),
            "@modelcontextprotocol/server-filesystem".into(),
            "/home/user/project".into(),
        ];
        let df = generate(Runner::Npx, &cmd, None, &[]).unwrap();
        assert!(df.contains("FROM alpine:latest"));
        assert!(df.contains("apk add --no-cache npm"));
        assert!(df.contains("RUN apk add --no-cache coreutils"));
        assert!(!df.contains("RUN apk add --no-cache python3"));
        assert!(df.contains("npm install -g @modelcontextprotocol/server-filesystem"));
        assert!(df.contains("ENTRYPOINT [\"npx\", \"-y\", \"@modelcontextprotocol/server-filesystem\", \"/home/user/project\"]"));
        assert!(df.contains(&format!(
            "LABEL org.opencontainers.image.version=\"{}\"",
            env!("CARGO_PKG_VERSION")
        )));
        assert!(df.contains("LABEL domcp.packages=\"\""));
    }

    #[test]
    fn test_generate_with_expose_port() {
        let cmd = vec!["uvx".into(), "mcp-server-sse".into()];
        let df = generate(Runner::Uvx, &cmd, Some(8080), &[]).unwrap();
        assert!(df.contains("EXPOSE 8080"));
        assert!(df.contains("RUN apk add --no-cache python3"));
        assert!(df.contains("ENTRYPOINT [\"uvx\", \"mcp-server-sse\"]"));
    }

    #[test]
    fn test_generate_with_packages() {
        let cmd = vec!["uvx".into(), "git-mcp-server".into()];
        let pkgs = vec!["git".to_string(), "openssh".to_string()];
        let df = generate(Runner::Uvx, &cmd, None, &pkgs).unwrap();
        assert!(df.contains("apk add --no-cache git openssh"));
        assert!(df.contains("RUN apk add --no-cache python3"));
        assert!(df.contains(&format!(
            "LABEL org.opencontainers.image.version=\"{}\"",
            env!("CARGO_PKG_VERSION")
        )));
        assert!(df.contains("LABEL domcp.packages=\"git,openssh\""));
    }
}
